# Generated by Django 5.0 on 2023-12-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='owner',
        ),
    ]
